//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MvcResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MvcResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Web.Resources.MvcResources", typeof(MvcResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A value for &apos;{0}&apos; is required but was not present in the request. ähnelt.
        /// </summary>
        internal static string BindingBehavior_ValueNotFound {
            get {
                return ResourceManager.GetString("BindingBehavior_ValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This model binder does not support the model type &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string Common_ModelBinderDoesNotSupportModelType {
            get {
                return ResourceManager.GetString("Common_ModelBinderDoesNotSupportModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value cannot be null or empty. ähnelt.
        /// </summary>
        internal static string Common_NullOrEmpty {
            get {
                return ResourceManager.GetString("Common_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The type &apos;{0}&apos; does not implement the interface &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string Common_TypeMustImplementInterface {
            get {
                return ResourceManager.GetString("Common_TypeMustImplementInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The &apos;Name&apos; property must be set. ähnelt.
        /// </summary>
        internal static string CommonControls_NameRequired {
            get {
                return ResourceManager.GetString("CommonControls_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The IControllerFactory &apos;{0}&apos; did not return a controller for a controller named &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string ControllerBuilder_FactoryReturnedNull {
            get {
                return ResourceManager.GetString("ControllerBuilder_FactoryReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The method &apos;{0}&apos; is an asynchronous completion method and cannot be called directly. ähnelt.
        /// </summary>
        internal static string ExpressionHelper_CannotCallCompletedMethod {
            get {
                return ResourceManager.GetString("ExpressionHelper_CannotCallCompletedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The method &apos;{0}&apos; is marked [NonAction] and cannot be called directly. ähnelt.
        /// </summary>
        internal static string ExpressionHelper_CannotCallNonAction {
            get {
                return ResourceManager.GetString("ExpressionHelper_CannotCallNonAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot route to class named &apos;Controller&apos;. ähnelt.
        /// </summary>
        internal static string ExpressionHelper_CannotRouteToController {
            get {
                return ResourceManager.GetString("ExpressionHelper_CannotRouteToController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expression must be a method call. ähnelt.
        /// </summary>
        internal static string ExpressionHelper_MustBeMethodCall {
            get {
                return ResourceManager.GetString("ExpressionHelper_MustBeMethodCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Controller name must end in &apos;Controller&apos;. ähnelt.
        /// </summary>
        internal static string ExpressionHelper_TargetMustEndInController {
            get {
                return ResourceManager.GetString("ExpressionHelper_TargetMustEndInController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The new model binding system cannot be used when a property whitelist or blacklist has been specified in [Bind] or via the call to UpdateModel() / TryUpdateModel(). Use the [BindRequired] and [BindNever] attributes on the model type or its properties instead. ähnelt.
        /// </summary>
        internal static string ExtensibleModelBinderAdapter_PropertyFilterMustNotBeSet {
            get {
                return ResourceManager.GetString("ExtensibleModelBinderAdapter_PropertyFilterMustNotBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The type &apos;{0}&apos; is not an open generic type. ähnelt.
        /// </summary>
        internal static string GenericModelBinderProvider_ParameterMustSpecifyOpenGenericType {
            get {
                return ResourceManager.GetString("GenericModelBinderProvider_ParameterMustSpecifyOpenGenericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The open model type &apos;{0}&apos; has {1} generic type argument(s), but the open binder type &apos;{2}&apos; has {3} generic type argument(s). The binder type must not be an open generic type or must have the same number of generic arguments as the open model type. ähnelt.
        /// </summary>
        internal static string GenericModelBinderProvider_TypeArgumentCountMismatch {
            get {
                return ResourceManager.GetString("GenericModelBinderProvider_TypeArgumentCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is no ViewData item with the key &apos;{0}&apos; of type &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string HtmlHelper_MissingSelectData {
            get {
                return ResourceManager.GetString("HtmlHelper_MissingSelectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The ViewData item with the key &apos;{0}&apos; is of type &apos;{1}&apos; but needs to be of type &apos;{2}&apos;. ähnelt.
        /// </summary>
        internal static string HtmlHelper_WrongSelectDataType {
            get {
                return ResourceManager.GetString("HtmlHelper_WrongSelectDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The value &apos;{0}&apos; is not valid for {1}. ähnelt.
        /// </summary>
        internal static string ModelBinderConfig_ValueInvalid {
            get {
                return ResourceManager.GetString("ModelBinderConfig_ValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A value is required. ähnelt.
        /// </summary>
        internal static string ModelBinderConfig_ValueRequired {
            get {
                return ResourceManager.GetString("ModelBinderConfig_ValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A binder for type {0} could not be located. ähnelt.
        /// </summary>
        internal static string ModelBinderProviderCollection_BinderForTypeNotFound {
            get {
                return ResourceManager.GetString("ModelBinderProviderCollection_BinderForTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The type &apos;{0}&apos; does not subclass {1} or implement the interface {2}. ähnelt.
        /// </summary>
        internal static string ModelBinderProviderCollection_InvalidBinderType {
            get {
                return ResourceManager.GetString("ModelBinderProviderCollection_InvalidBinderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The model of type &apos;{0}&apos; has a [Bind] attribute. The new model binding system cannot be used with models that have type-level [Bind] attributes. Use the [BindRequired] and [BindNever] attributes on the model type or its properties instead. ähnelt.
        /// </summary>
        internal static string ModelBinderProviderCollection_TypeCannotHaveBindAttribute {
            get {
                return ResourceManager.GetString("ModelBinderProviderCollection_TypeCannotHaveBindAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The binding context has a null Model, but this binder requires a non-null model of type &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string ModelBinderUtil_ModelCannotBeNull {
            get {
                return ResourceManager.GetString("ModelBinderUtil_ModelCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The binding context has a Model of type &apos;{0}&apos;, but this binder can only operate on models of type &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string ModelBinderUtil_ModelInstanceIsWrong {
            get {
                return ResourceManager.GetString("ModelBinderUtil_ModelInstanceIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The binding context cannot have a null ModelMetadata. ähnelt.
        /// </summary>
        internal static string ModelBinderUtil_ModelMetadataCannotBeNull {
            get {
                return ResourceManager.GetString("ModelBinderUtil_ModelMetadataCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The binding context has a ModelType of &apos;{0}&apos;, but this binder can only operate on models of type &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string ModelBinderUtil_ModelTypeIsWrong {
            get {
                return ResourceManager.GetString("ModelBinderUtil_ModelTypeIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The ModelMetadata property must be set before accessing this property. ähnelt.
        /// </summary>
        internal static string ModelBindingContext_ModelMetadataMustBeSet {
            get {
                return ResourceManager.GetString("ModelBindingContext_ModelMetadataMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The ControllerBuilder must return an IControllerFactory of type {0} if the MvcDynamicSessionModule is enabled. ähnelt.
        /// </summary>
        internal static string MvcDynamicSessionModule_WrongControllerFactory {
            get {
                return ResourceManager.GetString("MvcDynamicSessionModule_WrongControllerFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deserialization failed. Verify that the data is being deserialized using the same SerializationMode with which it was serialized. Otherwise see the inner exception. ähnelt.
        /// </summary>
        internal static string MvcSerializer_DeserializationFailed {
            get {
                return ResourceManager.GetString("MvcSerializer_DeserializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The provided SerializationMode is invalid. ähnelt.
        /// </summary>
        internal static string MvcSerializer_InvalidSerializationMode {
            get {
                return ResourceManager.GetString("MvcSerializer_InvalidSerializationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Format &apos;{0}&apos; is not supported. ähnelt.
        /// </summary>
        internal static string Resources_UnsupportedFormat {
            get {
                return ResourceManager.GetString("Resources_UnsupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unsupported Media Type: &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string Resources_UnsupportedMediaType {
            get {
                return ResourceManager.GetString("Resources_UnsupportedMediaType", resourceCulture);
            }
        }
    }
}
